version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    networks:
       - overlay
    depends_on:
      - php
      - php5
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/Www:/www:delegated

  php:
    build: ./php
    networks:
       - overlay
    depends_on:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - ~/Www:/www:delegated

  php5:
    build: ./php5
    networks:
       - overlay
    depends_on:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - ~/Www:/www:delegated

  mysql:
    build: ./mysql
    networks:
       - overlay
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/mysql.conf.d/custom.cnf

  redis:
    build: ./redis
    networks:
       - overlay
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  elasticsearch:
    build: ./elasticsearch
    networks:
      - overlay
    ports:
      - 9200:9200
      - 9300:9300

networks:
  overlay: