version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/Www:/www:delegated

  php:
    build: ./php
    depends_on:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - ~/Www:/www:delegated

  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  redis:
    build: ./redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  elasticsearch:
    build: ./elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  portainer:
    build: ./portainer
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
