version: "3"
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ~/Documents/rabbitmq:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_VHOST: my_vhost
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
            HOMEDRIVE: /var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        hostname: myRabbit

    nginx:
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ~/Documents/web:/Documents:delegated
        restart: always

    mysql:
        build: ./mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql/custom.mysql.cnf:/etc/mysql/conf.d/custom.mysql.cnf
            - ./mysql/data:/var/lib/mysql
        restart: always

    redis:
        build: ./redis
        ports:
            - 6379:6379
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/data:/data
        restart: always

    php74:
        build: ./php74
        ports:
            - 9501:9501
            - 9502:9502
        depends_on:
            - mysql
            - redis
        volumes:
            - ./php74/custom.php.ini:/usr/local/etc/php/conf.d/docker-php-custom.ini
            - ~/Documents/web:/Documents:delegated
        restart: always

    php80:
        build: ./php80
        ports:
            - 9503:9501
            - 9504:9502
        depends_on:
            - mysql
            - redis
        volumes:
            - ./php80/custom.php.ini:/usr/local/etc/php/conf.d/docker-php-custom.ini
            - ~/Documents/web:/Documents:delegated
        restart: always

    swoole:
        build: ./swoole
        ports:
            - 9505:9505
            - 9506:9506
        volumes:
            - ./swoole/custom.php.ini:/home/swoole.ini
            - ~/Documents/web:/www:delegated
        command: ["sleep","infinity"]
        restart: always