version: "3"
services:
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "~/Www:/www"
    links:
      - "php"

  php:
    build: "./php"
    volumes:
      - "~/Www:/www"
    links:
      - "mysql"
      - "redis"

  mysql:
    build: "./mysql"
    ports:
      - "3306:3306"
    volumes:
        - "./mysql/data:/var/lib/mysql"
        - "./mysql/custom.cnf:/etc/mysql/mysql.conf.d/custom.cnf"


  redis:
    build: "./redis"
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"


